name: PR Checks
on:
  pull_request:
    branches: [ "main" ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: "20" }

      - name: Install & build (frontend)
        run: |
          npm ci || npm install
          npm run build || echo "build step optional (dev-ready)"

      - name: Docker build (sanity)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
